default: &default
  adapter: 'mysql2'
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  reconnect: false

test:
  <<: *default
development:
  <<: *default
development_workers:
  <<: *default
production:
  <<: *default
  pool: 50
production_workers:
  <<: *default
  pool: 50
production_crawler:
  <<: *default
  pool: 50

